### ISSUE TITLE
Device deleted edge-case

### ISSUE THREAD

**Issue by lucasvdh** [balmli/com.samsung.wam#1]
I think there might be a change that if a device is deleted while the `async fetchState()` is being executed it will result in the fetch loop still existing after the device is gone.

A solution would be to add `this.deleted = true;` to the `onDeleted` method
https://github.com/balmli/com.samsung.wam/blob/95bab4e2d5ba5b038ba3397e7dda56415f40105b/lib/SamsungDevice.js#L60-L65

And checking for it at the start of the `fetchState` method.

**Comment by balmli** [comment]
Thanks!  You are right !

Will fix.
