### ISSUE TITLE
keeps turning on again after manually turning bar off

### ISSUE THREAD

**Issue by B3rt** [balmli/com.samsung.wam#3]
My HW-Q90R keeps switching back on again when the soundbar is turned off (using the original remote or buttons on bar).

When the app is disabled in Homey then the soundbar stays off (as it should be), but as soon as the app is enabled again and you turn off the soundbar (by remote) then it switches back on again.

When the soundbar is switched off using the APP then the soundbar stays off and does not switch on again.

This problem occurs even when there are no flows created yet!

**Comment by balmli** [comment]
Hi,

You can read about why this is happening in the community pages:
https://community.athom.com/t/app-samsung-wireless-audio-multiroom/30840/29
